name: Claim Free Games

on:
  schedule:
    - cron: '0 18 * * 4'
  workflow_dispatch:

jobs:
  claim:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dependencies
        run: npm install
      - name: Run Claimer
        env:
          EMAIL: ${{ secrets.EPIC_EMAIL }}
          PASSWORD: ${{ secrets.EPIC_PASSWORD }}
          TOTP: ${{ secrets.EPIC_TOTP_SECRET }}
        run: node claimer.js
